Repository BangFer/BangFer-Back_End, pull requests merged in 2024-07, with the labels that each got.

#136 [FEATURE] 카카오 프로필에서 이메일 가져오기 (#135)
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialSignupRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/KakaoService.java
Labels: ♻️ Refactor

#138 [REFACTOR] 성능 개선(쿼리&자원 점유) 및 로직 수정 (#137)
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsCommonService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/email/EmailService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/DetailCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticPositionDetailRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor

#140 [FEATURE] S3 설정 + 사진 업로드 (#139)
  build.gradle
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/ProfileController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/CreateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/OtherUserProfileResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/ProfileResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/UpdateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/Profile.java
  src/main/java/com/capstone/BnagFer/domain/accounts/repository/ProfileJpaRepository.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Board.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/BoardImage.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardImageRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardQueryService.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamCalendarController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamMembersController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/capstone/BnagFer/global/config/S3Config.java
  src/main/java/com/capstone/BnagFer/global/util/s3/S3Provider.java
  src/main/java/com/capstone/BnagFer/global/util/s3/dto/S3UploadRequest.java
Labels: ✨ Feature, ♻️ Refactor

#144 :ambulance: !hotfix: UserJpaRepository 삭제 (#143)
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
Labels: 🚑 !Hotfix

#146 [REFACTOR] @Builder.Default + API 명세
  src/main/java/com/capstone/BnagFer/domain/board/entity/Board.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Comment.java
  src/main/java/com/capstone/BnagFer/domain/report/controller/ReportController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
Labels: ♻️ Refactor

#149 [FEATURE] SWAGGER 화면 상 staff 전용 API, 신고 API 제목 추가(#148)
  src/main/java/com/capstone/BnagFer/domain/report/controller/ReportController.java
  src/main/java/com/capstone/BnagFer/domain/report/controller/StaffActionController.java
Labels: ♻️ Refactor

#151 [REFACTOR] 전술 세부 사항 리스트 RESPONSE에 추가 및 요구사항 반영 (#142)
  build.gradle
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/DetailUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
Labels: ♻️ Refactor

#153 [REFACTOR] 내 팀 정보 조회는 방장뿐만 아니라 모든 팀원들이 조회할 수 있게 리팩토링(#152)
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
Labels: ♻️ Refactor

#147 [FEATURE] 팀원 초대 수락 및 거절 구현(#130)
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamInviteController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamMembersController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamInviteRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamMemberRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamInviteResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamInvite.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamMember.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamInviteRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamMembersRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#155 [HOTFIX] TeamMembersRepository 에러 수정 (#154)
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamMembersRepository.java
Labels: 🚑 !Hotfix, ♻️ Refactor

#156 [FEATURE] 자유게시판 사용자 차단 구현 완료
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/BoardBlockRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardBlockResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardListDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/GetMyBoardBlockResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Board.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/BoardBlock.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardBlockRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardBlockQueryService.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardBlockService.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardQueryService.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#158 [REFACTOR] 내 팀 조회 & 전술 적용 리팩토링 (#157)
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/CUTeamRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ♻️ Refactor
