Repository BangFer/BangFer-Back_End, pull requests merged in 2024-03, with the labels that each got.

#22 [FEATUER] Spring Security, JWT 예외 처리 및 API 추가 (#21)
  http/AccountsTest.http
  http/http-client.env.json
  src/main/java/com/capstone/BnagFer/domain/accounts/annotation/AccountResolver.java
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/UserLoginResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/config/JwtAuthenticationFilter.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/config/JwtProvider.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/config/SecurityConfig.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/config/SecurityConfiguration.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/exception/SecurityCustomException.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/exception/TokenErrorCode.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/filter/JwtExceptionFilter.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/userdetails/CustomUserDetailService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/userdetails/CustomUserDetails.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/HttpResponseUtil.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/JwtProvider.java
  src/main/java/com/capstone/BnagFer/domain/accounts/repository/UserJpaRepository.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/AccountsQueryService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/AccountsService.java
  src/main/java/com/capstone/BnagFer/global/config/CorsConfig.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
Labels: ✨ Feature

#25 [FEATURE] 방구석팀 CRUD (#23)
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamRequest.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamResponse.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/GetTeamResponse.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/exception/TeamExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/SwaggerConfig.java
Labels: ✨ Feature

#26 [FEATURE] Tactic 작성, 수정, 삭제 구현 (#20)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/exception/TacticExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#28 [BUG] 버그 수정
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticRepository.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/SwaggerConfig.java
Labels: 🐛 BugFix

#35 [FEATURE] Tactic 피드백 수정 및 Read 추가 (#31)
  src/main/java/com/capstone/BnagFer/domain/accounts/service/AccountsServiceUtils.java
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#36 [REFACTOR] TeamDto Record로 변경 & AccountServiceUtils 적용 (#32)
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamRequest.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamResponse.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/GetTeamResponse.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ♻️ Refactor

#41 [REFACTOR] DTO 분리 (#37)
  http/AccountsTest.http
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticLike.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticPositionDetail.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor

#45 [Feature] 내팀에 전술 적용하기(#40)
  src/main/java/com/capstone/BnagFer/BnagFerApplication.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CUTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
Labels: ✨ Feature

#49 [REFACTOR]MyTeam에 tactic 적용 수정(#47)
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
Labels: ♻️ Refactor

#51 [FEATURE] 댓글 CUD 구현
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/CommentRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#53 [FEATURE] 좋아요 기능 CD (#52)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticLike.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/LikeRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ApiResponse.java
Labels: ✨ Feature
