Repository BangFer/BangFer-Back_End, pull requests merged in 2024-05, with the labels that each got.

#84 [REFACTOR] Accounts 서비스 리팩토링
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/Profile.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
Labels: ♻️ Refactor

#88 [FEATURE] 이메일 인증 & 인증 코드 확인
  build.gradle
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/email/EmailVerifyDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/email/EmailService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/EmailConfig.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
Labels: ✨ Feature

#89 [REFACTOR] Tactic 도메인 관련 리팩토링(#85)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor

#90 [REFACTOR] Team 엔티티 관련 리팩토링(#87)
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamMember.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamServiceUtils.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
Labels: ♻️ Refactor

#94 [REFACTOR] Team 엔티티 관련 리팩토링(#93)
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamMember.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamServiceUtils.java
Labels: ♻️ Refactor

#98 [REFACTOR] TeamTacticService 에러 수정(#97)
  src/main/java/com/capstone/BnagFer/domain/accounts/service/AccountsServiceUtils.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamServiceUtils.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
Labels: ♻️ Refactor

#105 [FEATURE] 팀 캘린더 CRUD 구현
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamCalendarController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamMembersController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/CUTeamRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamCalendarRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamMemberPositionRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamMemberRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/UpdateTeamCalendarRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/CUTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamCalendarResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamMemberPositionResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamMembersResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/CalendarEvent.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/exception/EventExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamCalendarRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamMembersRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#108 [REFACTOR] 로그인 유저 어노테이션 수정
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/CreateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/Profile.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
  src/main/java/com/capstone/BnagFer/global/annotation/LoginUser.java
  src/main/java/com/capstone/BnagFer/global/annotation/LoginUserArgumentResolver.java
  src/main/java/com/capstone/BnagFer/global/config/WebConfig.java
Labels: ♻️ Refactor

#110 [REFACTOR] 유저 서비스 리팩토링
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/oauth/KOAuthController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ChangeEmailRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ChangePwRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ForgotPwRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserLoginResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserSignupRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserSignupResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/UpdateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialSignupRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/Profile.java
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/accounts/repository/UserJpaRepository.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsCommonService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsQueryService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/KakaoService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/profile/ProfileService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/annotation/LoginUserArgumentResolver.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
  src/main/java/com/capstone/BnagFer/global/config/encoder/Pbkdf2PasswordEncoder.java
Labels: ♻️ Refactor

#111 [REFACTOR] TacticPositionDetail 엔티티 수정 및 코드 리펙토링
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/DetailCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/DetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/DetailUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticPositionDetail.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticPositionDetailRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ♻️ Refactor

#114 [FEATURE] FCM 푸시 알림 서비스 구현
  .gitignore
  build.gradle
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/RedisUtil.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/KakaoService.java
  src/main/java/com/capstone/BnagFer/domain/firebase/controller/FcmController.java
  src/main/java/com/capstone/BnagFer/domain/firebase/dto/FCMAlarmRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/firebase/exception/FirebaseExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/firebase/service/FcmAlarmService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/FCMConfig.java
Labels: ✨ Feature

#116 [REFACTOR] 좋아요 기능에 Redis 적용하기
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/RedisUtil.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor

#112 [REFACTOR] MyTeam 관련 리팩토링
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamCalendarController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamMembersController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/CUTeamRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamCalendarRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamMemberPositionRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamCalendarResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Role.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/Team.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamMember.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamCalendarRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/repository/TeamMembersRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ♻️ Refactor

#115 [FEATURE] 자유게시판 CRUD 구현
  src/main/java/com/capstone/BnagFer/domain/accounts/entity/User.java
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/BoardRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/CreateCommentRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/UpdateCommentRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/CommentResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/CreateBoardResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Board.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Comment.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Like.java
  src/main/java/com/capstone/BnagFer/domain/board/exception/BoardExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardCommentRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardLikeRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardQueryService.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ✨ Feature

#121 [BUG] 좋아요 개수 redis 적용 버그 수정 (#120)
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/RedisUtil.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: 🐛 BugFix

#119 [DOCS] swagger 상세 설정 (#118)
  http/AccountsTest.http
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/ProfileController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ChangeEmailRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ChangePwRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/ForgotPwRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/account/UserSignupRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/email/EmailVerifyDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/CreateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/profile/UpdateProfileRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialLoginRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/dto/social/UserSocialSignupRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/capstone/BnagFer/domain/accounts/jwt/util/JwtProvider.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/KakaoService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/email/EmailService.java
  src/main/java/com/capstone/BnagFer/domain/firebase/controller/FcmController.java
  src/main/java/com/capstone/BnagFer/domain/firebase/dto/FCMAlarmRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/firebase/service/FcmAlarmService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
  src/main/java/com/capstone/BnagFer/global/util/RedisUtil.java
Labels: 📝 Document

#128 [DOCS] swagger 상세 설정 - 전술, 팀, 자유 게시판
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/BoardRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/CreateCommentRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamCalendarController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/controller/TeamMembersController.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/CUTeamRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamCalendarRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamMemberPositionRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/UpdateTeamCalendarRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/CreateTeamTacticResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamCalendarResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/CalendarEvent.java
  src/main/java/com/capstone/BnagFer/domain/myteam/entity/TeamMember.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamCalendarService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CommentUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticCreateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticUpdateRequest.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/resources/application.yml
Labels: 📝 Document, ♻️ Refactor

#127 [REFACTOR] 댓글 개수 Redis 적용 (#124)
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/util/RedisUtil.java
Labels: ♻️ Refactor
