Repository BangFer/BangFer-Back_End, pull requests merged in 2024-08, with the labels that each got.

#166 [REFACTOR] 팀원 초대 시 닉네임으로 초대되게 끔 구현
  src/main/java/com/capstone/BnagFer/domain/accounts/repository/ProfileJpaRepository.java
  src/main/java/com/capstone/BnagFer/domain/accounts/repository/UserJpaRepository.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/request/TeamInviteRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/TeamInviteResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteService.java
Labels: ♻️ Refactor

#168 [FEATURE] 자유게시판 검색기능 구현
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/repository/BoardRepository.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardQueryService.java
Labels: ✨ Feature

#164 [FEATURE] 전술 게시판 검색 기능 구현 (#163)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/repository/TacticRepository.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
Labels: ✨ Feature

#170 [REFACTOR] 내 팀 목록 조회 시 팀 멤버, 그리고 해당 팀에 리더 포함 몇 명 있는지 조회할 수 있게끔 리팩토링
  src/main/java/com/capstone/BnagFer/domain/myteam/dto/response/GetTeamResponseDto.java
Labels: ♻️ Refactor

#172 [BUG] 버그 수정 및 firebase 삭제된거 복구 (#171)
  .gitignore
  src/main/java/com/capstone/BnagFer/domain/firebase/controller/FcmController.java
  src/main/java/com/capstone/BnagFer/domain/firebase/dto/FCMAlarmRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/firebase/exception/FirebaseExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/firebase/service/FcmAlarmService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
Labels: 🐛 BugFix, ♻️ Refactor

#174 [CI] appsec.yml 수정 (#173)
  appspec.yml
Labels: :earth_asia: Ci

#176 [REFACTOR] 댓글 삭제 시 - "삭제된 댓글입니다." 로 변경 (#175)
  src/main/java/com/capstone/BnagFer/domain/board/controller/BoardController.java
  src/main/java/com/capstone/BnagFer/domain/board/dto/response/BoardDetailResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/Comment.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticComment.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor

#178 [REFACTOR] S3 파일 확장자 같이 붙이게 수정 (#177)
  src/main/java/com/capstone/BnagFer/global/util/s3/S3Provider.java
Labels: ♻️ Refactor

#181 [REFACTOR] 전체 전술 목록 조회 시, 좋아요 댓글 수 드러나도록 수정 (#162)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
Labels: ♻️ Refactor

#182 [FEATURE] 전술게시판 차단 기능 구현 (#161)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/TacticDetailResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticQueryService.java
Labels: ✨ Feature, ♻️ Refactor
