Repository BangFer/BangFer-Back_End, pull requests merged in 2024-09, with the labels that each got.

#184 [FEATURE] FCM 알림 전송 추가 (#183)
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/domain/firebase/controller/FcmController.java
  src/main/java/com/capstone/BnagFer/domain/firebase/dto/FCMAlarmRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/firebase/exception/FirebaseExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/notification/controller/FcmNotificationController.java
  src/main/java/com/capstone/BnagFer/domain/notification/dto/FcmNotificationRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/notification/entity/FcmNotification.java
  src/main/java/com/capstone/BnagFer/domain/notification/exception/FcmNotificationExceptionHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/repository/FcmNotificationRepository.java
  src/main/java/com/capstone/BnagFer/domain/notification/service/FcmNotificationQueryService.java
  src/main/java/com/capstone/BnagFer/domain/notification/service/FcmNotificationService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ✨ Feature, ♻️ Refactor

#188 [REFACTOR] UserReport객체 생성 코드 리팩토링(#187)
  src/main/java/com/capstone/BnagFer/domain/report/dto/UserReportRequest.java
  src/main/java/com/capstone/BnagFer/domain/report/entity/UserReport.java
  src/main/java/com/capstone/BnagFer/domain/report/service/ReportService.java
Labels: ♻️ Refactor

#186 [REFACTOR] 알림 리팩토링 - 트랜잭션 분리 및 동시성 처리 (#185)
  build.gradle
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/capstone/BnagFer/domain/notification/entity/FcmNotification.java
  src/main/java/com/capstone/BnagFer/domain/notification/entity/NotificationTemplate.java
  src/main/java/com/capstone/BnagFer/domain/notification/event/CommentCreatedEvent.java
  src/main/java/com/capstone/BnagFer/domain/notification/event/PositionAllocatedEvent.java
  src/main/java/com/capstone/BnagFer/domain/notification/event/TacticCommentCreatedEvent.java
  src/main/java/com/capstone/BnagFer/domain/notification/event/TeamInviteCreatedEvent.java
  src/main/java/com/capstone/BnagFer/domain/notification/eventHandler/BaseNotificationEventHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/eventHandler/CommentEventHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/eventHandler/PositionAllocatedEventHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/eventHandler/TacticCommentEventHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/eventHandler/TeamInviteEventHandler.java
  src/main/java/com/capstone/BnagFer/domain/notification/service/FcmNotificationService.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/AsyncConfig.java
  src/main/java/com/capstone/BnagFer/global/config/RedisConfig.java
Labels: ♻️ Refactor

#195 [REFACTOR] 이메일 인증 전송 시 마다 인증 코드 달라지게 수정 (#194)
  src/main/java/com/capstone/BnagFer/domain/accounts/service/email/EmailService.java
Labels: 🐛 BugFix, ♻️ Refactor

#193 [REFACTOR] MyTeam&Board 부분 클린코딩 적용(#189)
  src/main/java/com/capstone/BnagFer/domain/board/dto/request/BoardBlockRequestDto.java
  src/main/java/com/capstone/BnagFer/domain/board/entity/BoardBlock.java
  src/main/java/com/capstone/BnagFer/domain/board/service/BoardBlockService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamInviteService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamMembersService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamQueryService.java
  src/main/java/com/capstone/BnagFer/domain/myteam/service/TeamTacticService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
Labels: ♻️ Refactor

#198 [FEATURE] 중복 이메일 존재 확인 API (#197)
  src/main/java/com/capstone/BnagFer/domain/accounts/controller/AccountsController.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsCommonService.java
  src/main/java/com/capstone/BnagFer/domain/accounts/service/account/AccountsService.java
  src/main/java/com/capstone/BnagFer/global/common/ErrorCode.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
Labels: ✨ Feature, ♻️ Refactor

#192 [REFACTOR] 효율적으로 redis를 활용하기 및 클린코딩 (#191)
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/util/RedisUtil.java
Labels: ♻️ Refactor

#200 [REFACTOR] 탈퇴 회원 복구 API를 allowedUrls에 추가하기 (#199)
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
  src/main/java/com/capstone/BnagFer/global/config/SecurityConfig.java
Labels: ♻️ Refactor

#203 [REFACTOR] 전술 복사 시, TacticPositionDetail 관한 부분 깊은 복사 처리 (#202)
  src/main/java/com/capstone/BnagFer/domain/tactic/controller/TacticController.java
  src/main/java/com/capstone/BnagFer/domain/tactic/dto/CopyTacticResponse.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/Tactic.java
  src/main/java/com/capstone/BnagFer/domain/tactic/entity/TacticPositionDetail.java
  src/main/java/com/capstone/BnagFer/domain/tactic/service/TacticService.java
Labels: ♻️ Refactor
